<?php

module_load_include('inc', 'wurfl', 'wurfl.class');
module_load_include('inc', 'wurfl', 'wurfl.parser');

function wurfl_init() {
	/*print $_SERVER['HTTP_USER_AGENT'];
	$ua = $_SERVER['HTTP_USER_AGENT'];;
	$wurfl = new wurfl();
	$matched = $wurfl->getDeviceCapabilities($ua);
	variable_set('ua', $ua);
	if($matched){
		echo "<pre>";
		print_r($wurfl->capabilities);
		echo "</pre>";
	}else{
		echo "<strong>This device could not be identified!</strong>";
	}
	
	die();*/
}


/**
 * Implementation of hook_menu().
 */
function wurfl_menu() {
  $items['admin/build/wurfl'] = array(
    'title' => 'WURFL',
    'access arguments' => array('administer wurfl'),
    'page callback' => 'wurfl_overview',
    'description' => 'Allows the creation and assignment of arbitrary wurfls to node types.',
    'file' => 'wurfl.admin.inc',
  );
  $items['admin/build/wurfl/list'] = array(
    'title' => 'List',
    'weight' => -10,
    'access arguments' => array('administer wurfl'),
    'page callback' => 'wurfl_overview',
    'file' => 'wurfl.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/build/wurfl/test'] = array(
    'title' => 'Test',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer wurfl'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_test_form'),
    'description' => 'WURFL Test Devices Capabilities',
    'file' => 'wurfl.admin.inc',
  );  
  $items['admin/build/wurfl/update'] = array(
    'title' => 'Update',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer wurfl'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_update_form'),
    'description' => 'WURFL Test Devices Capabilities',
    'file' => 'wurfl.admin.inc',
  );    
  $items['admin/build/wurfl/add'] = array(
    'title' => 'Add WURFL Device',
    'access arguments' => array('administer wurfl'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_add_form'),
    'file' => 'wurfl.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/build/wurfl/edit/%wurfl'] = array(
    'title' => 'Edit WURFL Device',
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer wurfl'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_edit_form', 4),
    'file' => 'wurfl.admin.inc',
  );  
  $items['admin/build/wurfl/delete/%wurfl'] = array(
    'title' => 'Delete wurfl',
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer wurfl'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_delete_form'),
    'file' => 'wurfl.admin.inc',
  );

  return $items;
}

function wurfl_perm() {
	return array('administer wurfl');
}