<?php

define('WURFL_XML', drupal_get_path('module', 'wurfl') . '/resources/wurfl.xml');
define('WURFL_CVS', 'http://wurfl.cvs.sourceforge.net/viewvc/wurfl/xml/wurfl.xml');
define('WURFL_IMAGES', drupal_get_path('module', 'wurfl') . '/resources/device_pix/');

module_load_include('inc', 'wurfl', 'includes/wurfl.class');
module_load_include('inc', 'wurfl', 'includes/wurfl.parser');


function wurfl_init() {
	$ua = $_SERVER['HTTP_USER_AGENT'];;
	$device = new wurfl();
	$matched = $device->getDeviceCapabilities($ua);
	$GLOBALS['wurfl_device'] = ($matched ? $device : new stdClass());
}

/**
* Implementation of hook_views_api().
*/
function wurfl_views_api() {
 return array(
   'api' => 2.0,
   'path' => drupal_get_path('module', 'wurfl') . '/includes',
 );
}


/**
 * Implementation of hook_menu().
 */
function wurfl_menu() {
  $items['admin/build/wurfl'] = array(
    'title' => 'WURFL',
    'access arguments' => array('administer wurfl'),
    'page callback' => 'wurfl_overview',
    'description' => 'Allows the creation and assignment of arbitrary wurfls to node types.',
    'file' => 'includes/wurfl.admin.inc',
  );
  $items['admin/build/wurfl/list'] = array(
    'title' => 'List',
    'weight' => -10,
    'access arguments' => array('administer wurfl'),
    'page callback' => 'wurfl_overview',
    'file' => 'includes/wurfl.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/build/wurfl/test'] = array(
    'title' => 'Test',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer wurfl'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_test_form'),
    'description' => 'WURFL Test Devices Capabilities',
    'file' => 'includes/wurfl.admin.inc',
  );
  $items['admin/build/wurfl/callback'] = array(
    'title' => 'Test',
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer wurfl'),
    'page callback' => 'wurfl_test_callback',
    'description' => 'WURFL Test Devices Capabilities',
    'file' => 'includes/wurfl.admin.inc',
  );     
  $items['admin/build/wurfl/update'] = array(
    'title' => 'Update',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer wurfl'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_update_form'),
    'description' => 'WURFL Test Devices Capabilities',
    'file' => 'includes/wurfl.admin.inc',
  );    
  $items['admin/build/wurfl/add'] = array(
    'title' => 'Add WURFL Device',
    'access arguments' => array('administer wurfl'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_add_form'),
    'file' => 'includes/wurfl.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/build/wurfl/edit/%wurfl'] = array(
    'title' => 'Edit WURFL Device',
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer wurfl'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_edit_form', 4),
    'file' => 'includes/wurfl.admin.inc',
  );  
  $items['admin/build/wurfl/delete/%wurfl'] = array(
    'title' => 'Delete wurfl',
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer wurfl'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_delete_form'),
    'file' => 'includes/wurfl.admin.inc',
  );

  return $items;
}


function wurfl_form_alter(&$form, &$form_state, $form_id) {

}

function wurfl_perm() {
	return array('administer wurfl');
}